### ISSUE TITLE
Error in Linux setup

### ISSUE THREAD

**Issue by alanocallaghan** [carpentries-incubator/high-dimensional-stats-r#160]
Pretty sure this is libcurl/libxml
```
ERROR: dependencies ‘Rsamtools’, ‘GenomicAlignments’ are not available for package ‘rtracklayer’
* removing ‘/home/smukherjee/R/x86_64-pc-linux-gnu-library/4.3/rtracklayer’
ERROR: dependency ‘rtracklayer’ is not available for package ‘GenomicFeatures’
* removing ‘/home/smukherjee/R/x86_64-pc-linux-gnu-library/4.3/GenomicFeatures’
ERROR: dependency ‘GenomicFeatures’ is not available for package ‘bumphunter’
* removing ‘/home/smukherjee/R/x86_64-pc-linux-gnu-library/4.3/bumphunter’
ERROR: dependency ‘bumphunter’ is not available for package ‘minfi’
* removing ‘/home/smukherjee/R/x86_64-pc-linux-gnu-library/4.3/minfi’
```

**Comment by mallewellyn** [comment]
Could link to this page in the setup: 
https://docs.posit.co/connect/admin/r/dependencies/

This may also fix the [igraph issue](https://carpentries-incubator.github.io/high-dimensional-stats-r/setup.html). I only suggested the current development install because I wanted to avoid installing all the system dependencies. I may be able to identify the essential packages to avoid this. However, there could be an argument for getting people to install all the dependencies in the link above so that their R is able to install packages in the future without too much intervention. I also think linking to that page is probably sensible because it covers a lot of distributions and probably also updates the dependencies. What do you think?

I can test whichever instructions we think are sensible next week when my Linux PC is fixed - currently using Windows in the meantime!!

**Comment by alanocallaghan** [comment]
Possibly, there is also this: https://r-sysreqs.josiahparry.com/index.html

**Comment by alanocallaghan** [comment]
Happy this'll be resolved with the PR, mostly, hard to predict any and all installation problems across systems tho
