### ISSUE TITLE
Review comments: Introduction to high-dimensional data

### ISSUE THREAD

**Issue by 3mmaRand** [carpentries-incubator/high-dimensional-stats-r#39]
https://carpentries-incubator.github.io/high-dimensional-stats-r/01-introduction-to-high-dimensional-data/index.html

I really like this introduction - great idea to explicitly define high dimensional data and give examples. There's good reiteration of the important points in the text.

I like Challenge 1. It would be great if the reasons for the correct and incorrect answers were given in the solution.

Challenge 2 is good. Perhaps "Examine the dataset" could be replaced by explicit questions that provoke examination e.g, How many patiants were recorded? What variables were measured? What are n and p?

Possibly just a style difference but I like to add brackets for function names in text, (e.g.,  variables using the `pairs()` function) and make package names bold (e.g.,  from the **`lasso2`** package)

"ratio of observations to features in a dataset is almost equal" might be clearer as "the number of observations and features in a dataset are almost equal".

As the figure isn't numbered, perhaps use "the figure on the left below" etc instead of 2a etc. Or number the fig.

I'm not sure what in Challenge 3 prompted:
\#\# correlation matrix for variables describing cancer/clinical variables
cor(Prostate[, c(1, 2, 4, 6, 9)])

Or what prompted the examination of the residuals.

Maybe be some specific questions could be added to the Challenge to help illustrate what happens in linear models when we include correlated explanatory variables.

I really like the rationale given for using different methods for hi-di data

 "Let’s install the minfi package" -> " Let’s load the minfi package"

I'm getting 404s minfi User's Guide.

Explain why you are using here?

**Comment by Alanocallaghan** [comment]
Also noticed "Bioconductor ethylation array analysis vignette." -> "Bioconductor methylation array analysis vignette."

**Comment by catavallejos** [comment]
Hi @3mmaRand, once again many thanks for all your comments. I have converted these into a list below so that we can provide a point-by-point response (which I will be updating in the coming days)

- [x] I really like this introduction - great idea to explicitly define high dimensional data and give examples. There's good reiteration of the important points in the text.

> Thank you so much for the positive feedback!

- [ ] I like Challenge 1. It would be great if the reasons for the correct and incorrect answers were given in the solution.

> Indeed, providing reasons for the answers will be informative. This has been addressed here d28e46344eb33dec2620e1d9562ef2c5253664df 

- [ ] Challenge 2 is good. Perhaps "Examine the dataset" could be replaced by explicit questions that provoke examination e.g, How many patiants were recorded? What variables were measured? What are n and p?

- [ ] Possibly just a style difference but I like to add brackets for function names in text, (e.g., variables using the pairs() function) and make package names bold (e.g., from the lasso2 package)

- [ ] "ratio of observations to features in a dataset is almost equal" might be clearer as "the number of observations and features in a dataset are almost equal".

- [ ] As the figure isn't numbered, perhaps use "the figure on the left below" etc instead of 2a etc. Or number the fig.

- [ ] I'm not sure what in Challenge 3 prompted:
## correlation matrix for variables describing cancer/clinical variables
cor(Prostate[, c(1, 2, 4, 6, 9)])

- [ ] Or what prompted the examination of the residuals.

- [ ] Maybe be some specific questions could be added to the Challenge to help illustrate what happens in linear models when we include correlated explanatory variables.

- [ ] I really like the rationale given for using different methods for hi-di data

- [ ] "Let’s install the minfi package" -> " Let’s load the minfi package"

- [ ] I'm getting 404s minfi User's Guide.

- [ ] Explain why you are using here?
