### ISSUE TITLE
Review comments: Regularised regression

### ISSUE THREAD

**Issue by 3mmaRand** [carpentries-incubator/high-dimensional-stats-r#49]
Regularised regression

https://carpentries-incubator.github.io/high-dimensional-stats-r/03-regression-regularisation/index.html

Overall, the approach in this episode which emphasises genuine understanding the methods, is one I really like. It is very long. There is quite a lot of necessary jargon and it would help if terms and the links between them were explained more fully. Overall, the steps and ideas could be broken down so that the rationale for each bit of code, output or exploration is more clear. Some of the outputs and figures are left to speak for themselves. I might be wrong but I think the average biologist with a standard stats/maths background would be overwhelmed. You could consider breaking this episode into separate episodes covering 1. what regularisation is and the rationale for it, including the concepts of scaling, and cross validation 2. Rigde and lasso regression. 3. Blending ridge regression and the LASSO. I think tidymodels is a whole other course - or alternatively just use that approach throughout.

I would expand the intro to explain what is going to be happening in this lesson in overview.

IIRC this episode is the first time the term "feature selection" is used - perhaps a sentence or two could be added to previous episodes to explain that that is the collective term for the processes covered?

In the The objective of a linear model section:

I think "minimises sum of the squared residuals." is clearer than "minimises the residual sum of squares."

"Mathematically, we can write that as" -> "Mathematically, we can write the sum of the squared residuals as"

Say what Horvath is.

I think this is the first time data have centred and scaled so it is not clear why that is being done.

in the Exercise 2.Fit a model on the training data matrix and training age vector, it might not appear "similar to what we did in the previous episode." because lmFit() was used then.

I would explain what the pred_lm v test_age figure shows explicitly.

In the Why would we want to restrict our model? section - first use of penalised and it is not made clear that penalised regression is what is discussed in the section above.

"2.Plot the predictions for each method against the ground truth. " -> "2. Plot predicted ages for each method against the observed ages"

Consider loosing the Bayesian section and possibly adding a sentence at the start of the episode that explains there are Bayesian and frequentist approaches and the one considered here is the latter.

If cross validation is not to be covered in detial here, consider leaving out the "Centering and scaling in cross-validation" detail.

**Comment by hannesbecher** [comment]
Implemented/covered elsewhere.

**Comment by mallewellyn** [comment]
For tracking, each of these points are addressed as follows.

In the commits above:
- jargon explained 
- IIRC this episode is the first time the term "feature selection" is used - perhaps a sentence or two could be added to previous episodes to explain that that is the collective term for the processes covered?
- In the Why would we want to restrict our model? section - first use of penalised and it is not made clear that penalised regression is what is discussed in the section above.
- I think "minimises sum of the squared residuals." is clearer than "minimises the residual sum of squares."
- Say what Horvath is.
- "Mathematically, we can write that as" -> "Mathematically, we can write the sum of the squared residuals as"
- I think this is the first time data have centred and scaled so it is not clear why that is being done.
- "2.Plot the predictions for each method against the ground truth. " -> "2. Plot predicted ages for each method against the observed ages"
- in the Exercise 2.Fit a model on the training data matrix and training age vector, it might not appear "similar to what we did in the previous episode." because lmFit() was used then.


Evident in current version (but unclear where committed):
- Consider loosing the Bayesian section and possibly adding a sentence at the start of the episode that explains there are Bayesian and frequentist approaches and the one considered here is the latter.
- I would expand the intro to explain what is going to be happening in this lesson in overview.
- Overall, the steps and ideas could be broken down so that the rationale for each bit of code, output or exploration is more clear. Outputs and figures explained.
> Captions added and figures are now annotated.

- I think tidymodels is a whole other course - or alternatively just use that approach throughout.
> Clearer now that this is just a note for interested parties from preceeding text.

- If cross validation is not to be covered in detail here, consider leaving out the "Centering and scaling in cross-validation" detail.
> No longer included
