### ISSUE TITLE
Pushed fixes to the wrong repo

### ISSUE THREAD

**Issue by hannesbecher** [carpentries-incubator/high-dimensional-stats-r#59]
I meant to make some code fixes in my own fork of this repo. I meant to send a pull request next. Instead, I pushed the changes to https://github.com/Ed-DaSH-Training/high-dimensional-stats-r I am surprised (and a bit pleased) I have permission to do that. See my commits: https://github.com/Ed-DaSH-Training/high-dimensional-stats-r/commits?author=hannesbecher

If these changes are fine, how would they get into this repo here and eventually online?

**Comment by Alanocallaghan** [comment]
If I go to that repo and look just below where branch info is shown I can see a contribute icon; you can open a PR from there and I'm happy to review it

If you are likely to be working on this repo more than a couple times I'm happy to give you dev access, though I'll probably review stuff for the time being just because I had to do a lot of very poorly documented bodges to get everything working
